# Generated by Django 4.2 on 2023-05-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='microbotics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=35)),
                ('batch', models.IntegerField()),
                ('product', models.CharField(max_length=25)),
            ],
        ),
    ]
